/*
 * storage open api
 * storage open api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xopenapi.storage.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 获取上传凭证
 */
@ApiModel(description = "获取上传凭证")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-05T18:52:44.565Z[GMT]")
public class CredentialsReq {
  public static final String SERIALIZED_NAME_CHANNEL = "channel";
  @SerializedName(SERIALIZED_NAME_CHANNEL)
  private String channel;

  public static final String SERIALIZED_NAME_PARAMS = "params";
  @SerializedName(SERIALIZED_NAME_PARAMS)
  private Object params;


  public CredentialsReq channel(String channel) {
    
    this.channel = channel;
    return this;
  }

   /**
   * 上传渠道，腾讯云：qcloud、阿里云：aliyun、七牛：qiniu
   * @return channel
  **/
  @ApiModelProperty(required = true, value = "上传渠道，腾讯云：qcloud、阿里云：aliyun、七牛：qiniu")

  public String getChannel() {
    return channel;
  }


  public void setChannel(String channel) {
    this.channel = channel;
  }


  public CredentialsReq params(Object params) {
    
    this.params = params;
    return this;
  }

   /**
   * 计算凭证参数，具体数据结构与上传渠道对应
   * @return params
  **/
  @ApiModelProperty(required = true, value = "计算凭证参数，具体数据结构与上传渠道对应")

  public Object getParams() {
    return params;
  }


  public void setParams(Object params) {
    this.params = params;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CredentialsReq credentialsReq = (CredentialsReq) o;
    return Objects.equals(this.channel, credentialsReq.channel) &&
        Objects.equals(this.params, credentialsReq.params);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, params);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CredentialsReq {\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

