/*
 * Storage open api
 * storage open api
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateUploadCredentialsReq;
import org.openapitools.client.model.CreateUploadCredentialsRsp;
import org.junit.Test;
import java.util.HashMap;
import java.util.Map;

/**
 * API tests for CredentialsApi
 */
public class CredentialsApiTest {

    private final CredentialsApi api = new CredentialsApi("0b88b62444694267af5f975782440843", "59a9b6f2210340fabb280764fba6d72c");


    /**
     * 获取上传凭证 credentials
     * <p>
     * 获取上传凭证 credentials
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        CreateUploadCredentialsReq body = new CreateUploadCredentialsReq();
        body.channel("qcloud");
        Map<String, Object> extra = new HashMap<>();
        extra.put("region", "ap-guangzhou");
        extra.put("bucket", "mofanshow-avatar-1252461817");
        body.extra(extra);

        CreateUploadCredentialsRsp response = api.create(body);
        System.out.println(response);
        // TODO: test validations
    }

}
