/*
 * Storage open api
 * storage open api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateUploadCredentialsReq;
import org.openapitools.client.model.CreateUploadCredentialsRsp;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CredentialsApi
 */
@Ignore
public class CredentialsApiTest {

    private final CredentialsApi api = new CredentialsApi();

    
    /**
     * 获取上传凭证 credentials
     *
     * 获取上传凭证 credentials
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        String timestamp = null;
        String noncestr = null;
        String signature = null;
        CreateUploadCredentialsReq body = null;
        CreateUploadCredentialsRsp response = api.create(timestamp, noncestr, signature, body);

        // TODO: test validations
    }
    
}
